### ISSUE TITLE
make dataset details

### ISSUE THREAD

**Issue by hwh-hit** [leon-liangwu/MaskYolo_Caffe#19]
hi, glad to see your work here, but i am new at caffe. can u show me more details about how to make my own dataset(mask only)?  e.g. label tools（标注工具？）,format of dataset . thanks a lot

**Comment by leon-liangwu** [comment]
@hwh-hit 
hi, the data script tools have been provided in scripts/ dir. 
For the detection target, you can transform your labels to darknet Yolo format. Images are in JPEGImages/ and labels in labels/. Every image has a label file xxx.txt in which every line is a box 'class x y w h'. You need to generate a .txt file in which every line is the path to the image.
For mask regression, you need to transform your data to coco format.

**Comment by hwh-hit** [comment]
Hi, thanks for your reply. instance segmentation is the thing i want to do, keypoints is not necessary for me and i don't have a label 'person'. i have dataset made by labelme and i have transferred them to coco format. so createdata_mask_kps.py is not fit for me, such a pity. Another question, can i only do the instances segmentation with your code? thanks again

**Comment by leon-liangwu** [comment]
@hwh-hit 
Ok, I see. Actually, this repo support only training the instance segmentation task. You can find a layer in src/caffe/layers/mask_box_data_layer.cpp which does not use keypoints ground truth.
The lmdb tool will be upload if you need. 
Actually, you can modify scripts/createdata_mask_kps.py to generate lmdb without keypoints.

**Comment by hwh-hit** [comment]
thanks for your reply. yes, i need it, hah. actually i have tried to modified scripts/createdata_mask_kps.py, but something wrong. By the way, wechat :991185721 ,just for Technical Communication if it is convenient.

**Comment by leon-liangwu** [comment]
@hwh-hit 
OK. 
I will update the script this week. Thanks for your support.

**Comment by hwh-hit** [comment]
@leon-liangwu 
OK, when you update the script ,i will have a try with your code and my data, then give you a feedback.
thanks for your reply.

**Comment by hwh-hit** [comment]
hi, any updates?

**Comment by leon-liangwu** [comment]
@hwh-hit ,
I have updated it in scripts/createdata_mask_only.py. The usage is as same as createdata_mask_kps.py. Have fun.
