### ISSUE TITLE
path/to/train.txt

### ISSUE THREAD

**Issue by marekjaszuk** [leon-liangwu/MaskYolo_Caffe#20]
Hi,
I'm trying to train the object detector, but I got stuck on generating the lmdb through the command:
# generate lmdb for detection
sh ./scripts/convert_detection.sh  /path/to/train.txt /path/to/lmdb 
The problem is that I do not know what the /path/to/train.txt should poin to? I have the VOC data, and I was trying to point various locations and .txt files, but I still get the following message:
convert_dec_data.cpp:86] A total of 0 images.
So as it seems it does not find the proper file.

**Comment by leon-liangwu** [comment]
@marekjaszuk 
Firstly, you need to use voc_label.py to generate train.txt which is a list of the image paths. Every line of this train.txt is a path to an image. 
Then you replace  /path/to/train.txt to the real path to your train.txt.
