### ISSUE TITLE
download pretrained models

### ISSUE THREAD

**Issue by xxd1992** [leon-liangwu/MaskYolo_Caffe#22]
Can you send a copy of the download to my email（2450896840@qq.com） ? The website can't be accessed.

**Comment by leon-liangwu** [comment]
@xxd1992 
Hi, I have updated the readme file and added Baidu Cloud link for you to download. Enjoy!

**Comment by xxd1992** [comment]
Thank you for your reply, and Baidu cloud link extraction code error, can you give another one?
