### ISSUE TITLE
训练KpsData，结果只有检测框，没有mask。

### ISSUE THREAD

**Issue by BaofengZan** [leon-liangwu/MaskYolo_Caffe#32]
作者您好，问题如题。  在训练时prop_num为64，batchsize=4(显卡1060 6g)。
step1 为 100000次， step2训练 80000。

**Comment by leon-liangwu** [comment]
@BaofengZan 你的prop_num 太大了， 这个值约等于你这个batch里object的数目。 你的batchsize为4，那么一般来说prop_num也为4。但是我建议你可以弄大一点的batchsize。

**Comment by BaofengZan** [comment]
@leon-liangwu ok 谢谢回复，我重新训练下。

**Comment by BaofengZan** [comment]
@leon-liangwu,您好，我又来了。  还是有很多问题。  能否添加你的私人账号，能实时请教？ 如果不方便的话，可以使用邮箱么？ 我qq的邮箱是2072188496@qq.com(也可以添加qq)  谢谢！

**Comment by BaofengZan** [comment]
@leon-liangwu  您好，我重新训练了好多次，使用不同的参数，现在还是只有检测框，没有mask框。
同样我也只训练了maks数据的模型，结果仍然没有mask。  
由于我显卡内存小。我batchsize设置的是8 pro_num设置8和16两种，都测试了，结果都是没有mask。

`

layer {
  name: "region_loss"
  type: "RegionLoss"
  bottom: "conv_out"
  bottom: "label"
  top: "region_loss"
  loss_weight: 1.0
  region_loss_param {
    num_class: 0
    num_object: 3
    object_scale: 5.0
    noobject_scale: 1.0
    class_scale: 1.0
    coord_scale: 1.0
    softmax: false
    rescore: false
    with_mask: true
    with_kps: false
    mask_w: 320
    mask_h: 224
    anchor_x: 1.33
    anchor_x: 2.86
    anchor_x: 7.25
    anchor_y: 3.05
    anchor_y: 7.02
    anchor_y: 10.73
    thresh: 0.6
    bias_match: true
  }
}

layer {
  name: "decode_roi"
  type: "DecodeRois"
  bottom: "conv_out"
  bottom: "label"
  top: "rois"
  top: "roi_labels"
  top: "bbox_targets"
  top: "bbox_inside_weights"
  top: "bbox_outside_weights"
  top: "mask_targets"
  top: "kps_targets"
  decode_rois_param {
    num_class: 0
    num_object: 3
    prop_num: 16
    with_mask: true
    with_kps: false
    mask_w: 320
    mask_h: 224
    target_size: 28
    anchor_x: 1.33
    anchor_x: 2.86
    anchor_x: 7.25
    anchor_y: 3.05
    anchor_y: 7.02
    anchor_y: 10.73
    thresh: 0.2
    net_w: 320
    net_h: 224
  }
}

`
上面是中间的一些设置，您看有什么问题么？

在训练时，学习率设置了0.01和0.001，训练loss基本在1左右。  
期待您的回答。
