### ISSUE TITLE
No mask result

### ISSUE THREAD

**Issue by guods** [leon-liangwu/MaskYolo_Caffe#33]
I train step1 with batchsize 32 and prop_num 32,  step2 with batchsize 16 and prop_num 32; but when I test the model at 80000 iter, there are only the detection results and no the mask result.

**Comment by leon-liangwu** [comment]
@guods In step2, please make prop_num equal to batchsize too.

**Comment by guods** [comment]
> @guods In step2, please make prop_num equal to batchsize too.

Thanks for your reply, I will  try it.
