### ISSUE TITLE
请问下这个库目前的精度和速度怎么样？

### ISSUE THREAD

**Issue by yiran-THU** [leon-liangwu/MaskYolo_Caffe#35]
非常感谢up主的工作。
请问下up主有没有做过测试，这个库包含的算法，在coco/VOC等公开库上的精度，以及其在1080等GPU上的速度？
如果有，希望能提供下，谢谢！

**Comment by leon-liangwu** [comment]
@yiran-THU  Hi, 目前并没有在公开数据集上测过，一直只是做了人体的检测和分割。
在1080上能达到实时，有demo你可以试试。
谢谢支持。
