### ISSUE TITLE
双卡训练maskyolo, 没有分割结果

### ISSUE THREAD

**Issue by guods** [leon-liangwu/MaskYolo_Caffe#37]
从coco数据集拿出2000张图片生成mask lmdb, 两个TiTan X 训练我的模型,  batch size 32, prob_num 32. step2迭代7000时，测试图片时仅有检测框；迭代 20000时，测试图片什么都没有。

**Comment by leon-liangwu** [comment]
请贴出你step1 和step2 的prototxt，
上传到云， 我下载一下看看吧。

**Comment by guods** [comment]
@leon-liangwu  



[step1和step2.zip](https://github.com/leon-liangwu/MaskYolo_Caffe/files/3856544/step1.step2.zip)
请帮忙看下train.prototxt的问题

**Comment by leon-liangwu** [comment]
@guods 无法解压你的zip
![image](https://user-images.githubusercontent.com/7507360/69019939-c5e15700-09ed-11ea-90dd-9a0b4b5dab30.png)

**Comment by guods** [comment]
[mb_body_mask_train_step2.txt](https://github.com/leon-liangwu/MaskYolo_Caffe/files/3856558/mb_body_mask_train_step2.txt)
[mb_body_mask_train_step1.txt](https://github.com/leon-liangwu/MaskYolo_Caffe/files/3856559/mb_body_mask_train_step1.txt)
![Uploading step2_loss.jpg…]()

**Comment by leon-liangwu** [comment]
@guods  你用的是哪一个script做的lmdb，有改动吗？

**Comment by guods** [comment]
createdata_mask_only.py，只改了coco数据集年份，用的是2017

**Comment by leon-liangwu** [comment]
@guods 
我试一试找出问题，因为这个project是我很久以前做的，所以需要一些时间，请谅解。谢谢支持。有发现会早点告诉你。

**Comment by guods** [comment]
好的，感谢您的回复。

**Comment by leon-liangwu** [comment]
@guods  hi, 我想我已经解决了mask训练的问题，请从做lmdb开始重新执行一遍，我相信有不错的结果。谢谢支持。

**Comment by guods** [comment]
@leon-liangwu 感谢你帮我解决问题，你能告诉我哪里出了问题吗

**Comment by leon-liangwu** [comment]
create_mask.py这个脚本有个地方错了，把mask乘了一个系数，是用作debug显示的，现在系数为1 就好了。

**Comment by leon-liangwu** [comment]
@guods  Hi, if you have any other problems with this repo, please feel free to let me know.
If you can train the model successfully, please close the issue to make me informed that the issue has been settled.
