### ISSUE TITLE
taget_size问题请教

### ISSUE THREAD

**Issue by BaofengZan** [leon-liangwu/MaskYolo_Caffe#47]
@leon-liangwu   感谢你的工作。 我在研究代码时，有个疑问，这里的target_size设置为28的依据是什么？  https://github.com/leon-liangwu/MaskYolo_Caffe/blob/423094eb4245e3aa372e2b7e7e574321465a2de3/models_maskyolo/mb_body_mask/mb_body_mask_train_step1.prototxt#L3175

**Comment by leon-liangwu** [comment]
每个物体roi_pooling 之后是7x7大小的feature map，对于分割问题，target_size 不能太小，但是太大又会影响速度。试验之后，28x28是比较快，并且结果也还可以的选择。当然你也可以选用更大的target，比如56x56。

**Comment by BaofengZan** [comment]
@leon-liangwu  感谢回复。
