### ISSUE TITLE
修改网络的输入尺寸

### ISSUE THREAD

**Issue by guods** [leon-liangwu/MaskYolo_Caffe#48]
原来网络输入尺寸是320*224，我想将网络的640*448训练模型， 除了修改输入尺寸还需要修改哪些参数？

**Comment by leon-liangwu** [comment]
you need to change all the corresponding values in MaskData , region_loss and decoderoi layers, and also you need to change the anchor values in region loss and decode roi layers bacause these values represent the box size on the feature map.

**Comment by guods** [comment]
感谢您的回复，我已修改在训练，期待有个好结果
