### ISSUE TITLE
替换特征提取网路，几个参数不太理解

### ISSUE THREAD

**Issue by guods** [leon-liangwu/MaskYolo_Caffe#50]
我想将MobilenetV2替换成Resnet50，为了能训练起来，将RegionLoss层和decode_roi层中的num_object=3改成num_object=4, anchor_x和anchor_y重新计算成四对， 以及num_coord由默认的4, 我在train.prototxt中手动传入参数；我想知道这两个参数和prop_num的具体含义，看代码没太看懂。

**Comment by leon-liangwu** [comment]
这些都和yolo是一样的。feature map 的output是 num_object * (1+4+num_class)  ,只有一个类的时候num_class =0, 大于1的时候，num_class=类个数，num_object 为anchor个数。num_coord 就是x, y, w, h 这四个值，prop_num，是选取用来做mask regression的box proposal的个数，我这里一般等于batch_size大小，因数据集中target多少而变。

**Comment by guods** [comment]
@leon-liangwu 非常感谢你的回答。

**Comment by guods** [comment]
@leon-liangwu 


[resnet50_train_step1.txt](https://github.com/leon-liangwu/MaskYolo_Caffe/files/3925098/resnet50_train_step1.txt)
我替换了特征提取网络，不收敛，你能帮我看看改的网络有什么问题吗

**Comment by leon-liangwu** [comment]
I think you may need to firstly train a detection model without the mask regression part for finetuning.

**Comment by guods** [comment]
[mb_v2_t4_cls5_deploy.txt](https://github.com/leon-liangwu/MaskYolo_Caffe/files/3931121/mb_v2_t4_cls5_deploy.txt)
你提供的mb_v2_t4_yolo.caffemodel对应的deploy文件是\models_maskyolo\mb_v2_t4_cls5_yolo\mb_v2_t4_cls5_deploy.prototxt吗
mb_v2_t4_cls5_deploy.prototxt中特征提取层到conv5/2/sum,但是caffemodel中的特征提取层到conv6/0/ds1/det?你能帮我确认一下吗
