### ISSUE TITLE
no field named "roi_gen_param"

### ISSUE THREAD

**Issue by ytf95** [leon-liangwu/MaskYolo_Caffe#53]
Thank you for your excellent work!

I have a problem that when I run, the terminal prompt has no field named "roi_gen_param" .

/home/fly/Pictures/Screenshot from 2020-02-24 13-07-50.png

Thank you very much for your answer！

**Comment by leon-liangwu** [comment]
@ytf95  Could you please upload the screenshot again?
I guess the issue is caused because you did not add the pycaffe path of this repo to the PYTHONPATH env variable.

**Comment by ytf95** [comment]
> @ytf95 Could you please upload the screenshot again?
> I guess the issue is caused because you did not add the pycaffe path of this repo to the PYTHONPATH env variable.

![Screenshot from 2020-02-24 13-07-50](https://user-images.githubusercontent.com/50893777/75132158-e7e72580-5710-11ea-8ed0-8970c5e457eb.png)

Thanks for your reply


Similar to: roi_xxx_param and so on have similar problems

**Comment by leon-liangwu** [comment]
@ytf95 I guess you should set the PYTHONPATH rightly.

**Comment by ytf95** [comment]
> @ytf95 I guess you should set the PYTHONPATH rightly.

So how do I set the right path correctly?


Is it /home/fly/MaskYolo_Caffe/caffe-maskyolo/python?

**Comment by leon-liangwu** [comment]
like this:
```
export PYTHONPATH="/home/fly/MaskYolo_Caffe/caffe-maskyolo/python":$PYTHONPATH
```

**Comment by ytf95** [comment]
> like this:
> 
> ```
> export PYTHONPATH="/home/fly/MaskYolo_Caffe/caffe-maskyolo/python":$PYTHONPATH
> ```

I can succeed in your work.


However, I have applied the model file to other places, so this problem arises. I think this idea of mine may be a wrong idea.


Thank you very much for your answer.
